apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: devopsapp  # Changed this to match the deployment label
  ports:
    - port: 8080
      targetPort: 8080
      # Optional field; uncomment if you want to specify a nodePort
      # nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment
  labels:
    app: devopsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsapp
  template:
    metadata:
      labels:
        app: devopsapp
    spec:
      containers:
      - name: devopsapp
        image: trialann9ye.jfrog.io/frontend/appb:10
        ports:
        - containerPort: 8080
